✅ new migration tests for skate-park and rental model
Brazlucas/skate-park-management-laravel-11 pull request #9
Opened 2024-07-28 19:41 UTC by Brazlucas

2024-07-29 21:28 UTC, Mourishitz approved these changes
BOAAAA

uma sugestão (não precisa fazer isso agora) maaaas
é interessante a gente mapear erros também, por exemplo, se um parque já estiver alugado, caso outro usuário tente alugar, ele deve conseguir? Se sim, um teste pra isso, se não, um teste para garantir que o erro jogado seja o correto

2024-07-30 08:01 UTC, matheusodilon approved these changes
Parabens, meu chapa!

2024-08-06 20:45 UTC, Mourishitz requested changes
Show! Só umas alteraçoes ai e ja ta otimo

2024-08-06 20:45 UTC, Mourishitz commented on app/Http/Controllers/RentalController.php
> +        ]);
```suggestion
```

em `public function store(Request $request)` troque `Request` por uma classe que extenda o `Request`

Dentro dessa classe que extende Request (ex.: StoreRentalRequest.php) deve haver um método rules() que retorna um array.

Esse array de rules pode ser identico a essas linhas, assim, no momento que a requisição for feita, o Laravel automaticamente irá validar os dados de request com as regras da sua classe (abstraindo responsabilidade do Controller para o Request)

2024-08-06 20:45 UTC, Mourishitz commented on app/Http/Controllers/RentalController.php
> +        ]);
Exemplo de classe:

```
<?php

namespace App\Api\Product\Requests;

use Illuminate\Http\Request;

class StoreRequestExample extends Request
{
    public function rules(): array
    {
        return [
            'skate_park_id' => 'required|exists:skate_parks,id',
            'renter_name' => 'required|string|max:255',
            'start_time' => 'required|date',
            'end_time' => 'required|date|after:start_time',
        ];
    }
}
```

2024-08-06 20:45 UTC, Mourishitz commented on app/Http/Controllers/RentalController.php
>      public function store(Request $request)
```suggestion
    public function store(StoreExampleRequest $request)
```

2024-08-06 20:45 UTC, Mourishitz commented on app/Http/Controllers/RentalController.php
> +        $this->rentalRepository = $rentalRepository;
```suggestion
```

2024-08-06 20:45 UTC, Mourishitz commented on app/Http/Controllers/RentalController.php
> +    protected $rentalRepository;
```suggestion
```

2024-08-06 20:45 UTC, Mourishitz commented on app/Repositories/Contracts/RentalRepositoryInterface.php
> +    public function delete($id);
```suggestion
    public function all(): Collection;
    public function find($id): Model;
    public function create(array $data): Model;
    public function update($id, array $data): Model|bool;
    public function delete($id): bool;
```

2024-08-12 23:15 UTC, Mourishitz approved these changes
<img src="https://media0.giphy.com/media/SYzDscQMN98G0LUHib/giphy.gif"/>

2024-08-13 02:11 UTC, merged